---
title: "Curriculum Vitae"
format: html
---

## Education

- **M.A. Economics and Education**, Teachers College, Columbia University  
- **B.A. Economics & Russian Studies**, Wheaton College  
- **Certificate in Data Visualization**, The New School

---

## Current Role

**Associate Director of Institutional Research and Assessment**  
_Massachusetts College of Pharmacy and Health Sciences (July 2022–Present)_

- Built and manages the university’s IR database with SQL and Azure
- Leads course evaluations, data governance, and accreditation reporting
- Presents institutional dashboards and supports strategic planning

---

## Previous Roles

**Assistant Director of Institutional Research**  
_Massachusetts College of Pharmacy and Health Sciences (June 2020–July 2022)_

**Research & Business Analyst, Office of Institutional Research and Decision Support**  
_The New School (October 2018–June 2020)_

**Data Analyst, Office of Student Success**  
_The New School (January 2017–October 2018)_

**Workforce Management Analyst | NYC 311**  
_Research Foundation ofThe City University of New York (May 2015–January 2017)_

**Data Analyst, Research/Analytic Consultant | New York City Department of Education**  
_School Professionals (October 2014–May 2015)_

---

## Skills

- **Languages**: R, SQL, Python, SPSS  
- **Tools**: Tableau, Quarto, Qualtrics, Azure, Jupyter, Visual Studio Code  
- **ERP/Database**: Workday, Ellucian Banner, DBeaver

---

## Memberships & Involvement

- North East Association for Institutional Research (NEAIR)  
- EDUCAUSE  
- Association for Institutional Research (AIR)  
- Faculty Development & Data Governance Committees (MCPHS)  

---

## Certifications

- Data Governance Essentials – EDUCAUSE  
- Leadership Management Program – Colleges of the Fenway
